import React from 'react'
import Footer from '../component/SalesPageComponent/Footer'
import NavBar from '../component/SalesPageComponent/NavBar'

export default function contactus() {
    return (
        <div className='w-full'>
            {/* <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            <div>
                <NavBar tab='contactus' />
            </div>
            <div className='w-full flex justify-center items-center' > 
                <div className='w-full flex flex-col items-center ' >
                    <div>
                        <p style={{color:'#002343'}} className='w-389px font-CircularStd-Medium text-5xl' >Contact us</p>
                        <p style={{color:'#333333'}} className='w-389px font-CircularStd-Light mt-4'>Do well to reach out to us incase you have any challenge and we will gladly assist you.</p>
                        <div className='flex mt-10 items-center' >
                            <div style={{backgroundColor: '#EAF6FF'}} className='w-10 h-10 rounded-full flex justify-center items-center' >
                                <svg width="16" height="7" viewBox="0 0 16 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M4.32439 5.20573L4.17859 4.47673C4.14948 4.3312 4.15196 4.17973 4.22661 4.05147C4.47111 3.63137 5.31367 2.7095 8 2.7095C10.6863 2.7095 11.5289 3.63137 11.7734 4.05147C11.8481 4.17973 11.8505 4.3312 11.8214 4.47673L11.6756 5.20573C11.5671 5.74853 11.9191 6.27653 12.4619 6.38513L14.5272 6.7982C15.0009 6.89293 15.4749 6.6362 15.6543 6.1876L15.8673 5.6552C16.029 5.2508 16.0422 4.80213 15.9045 4.38887C15.7894 4.0436 15.6362 3.71207 15.3913 3.44293C14.6193 2.59479 12.4459 0.776693 8 0.776693C3.55405 0.776693 1.38073 2.59479 0.608765 3.44293C0.363804 3.71207 0.210626 4.0436 0.0955447 4.38887C-0.0422 4.80213 -0.0290145 5.2508 0.132759 5.6552L0.345713 6.1876C0.525147 6.6362 0.999073 6.89293 1.47283 6.7982L3.53816 6.38513C4.08094 6.27653 4.43295 5.74853 4.32439 5.20573Z" fill="#002343"/>
                                </svg>
                            </div>
                            <p style={{color:'#017DC3'}} className=' ml-3 font-CircularStd-Light'>0700 000 0000</p>
                        </div> 
                        <div className='flex mt-4 items-center' >
                            <div style={{backgroundColor: '#EAF6FF'}} className='w-10 h-10 rounded-full flex justify-center items-center' >
                                <svg width="14" height="12" viewBox="0 0 14 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M12.6972 0.666664H1.30277C0.583273 0.666664 0 1.24994 0 1.96944C0 2.40502 0.217693 2.8118 0.580127 3.05342L1.37017 3.5801L5.8906 6.59373C5.9746 6.64973 6.06173 6.69873 6.15127 6.74066C6.778 7.0346 7.5216 6.9856 8.1094 6.59373L12.6299 3.5801L13.4199 3.05342C13.7823 2.8118 14 2.40502 14 1.96944C14 1.24994 13.4167 0.666664 12.6972 0.666664ZM0.333333 5.33333C0.333333 5.19413 0.347553 5.05826 0.374613 4.92713C0.45096 4.55708 0.889447 4.46148 1.20381 4.67106L5.3359 7.4258C6.3436 8.0976 7.6564 8.0976 8.66413 7.4258L12.7962 4.67106C13.1105 4.46148 13.5491 4.55708 13.6254 4.92713C13.6525 5.05826 13.6667 5.19413 13.6667 5.33333V10C13.6667 10.7364 13.0697 11.3333 12.3333 11.3333H1.66667C0.930287 11.3333 0.333333 10.7364 0.333333 10V5.33333Z" fill="#002343"/>
                                </svg>
                            </div>
                            <p style={{color:'#017DC3'}} className=' ml-3 font-CircularStd-Light'>contact@Vaultafrica.co</p>
                        </div> 
                    </div>
                </div>
                <div className='w-full relative' >
                    <div style={{width:'400px'}} className='relative mb-14 ml-14 z-40' > 
                        <img style={{width: '400px', borderTopRightRadius: '40px', borderBottomRightRadius: '40px'}} src='/assets/images/contactImage.png' alt='Hero' />
                    </div>
                    <div style={{height: '300px', backgroundColor: '#002343'}} className=' absolute bottom-0 w-full - rounded-t-full ' >

                    </div>
                </div>
            </div>
            <div>
                <Footer />
            </div>
        </div>
    )
}
