import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import FifthSection from '../component/SalesPageComponent/FifthSection'
import Footer from '../component/SalesPageComponent/Footer'
import FourthSection from '../component/SalesPageComponent/FourthSection'
import HeroSection from '../component/SalesPageComponent/HeroSection'
import NavBar from '../component/SalesPageComponent/NavBar'
import SecondSection from '../component/SalesPageComponent/SecondSection'
import SixthSection from '../component/SalesPageComponent/SixthSection'
import ThirdSection from '../component/SalesPageComponent/ThirdSection'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar tab='' />
      </div>
      <HeroSection />
      <div>
        <SecondSection />
      </div>
      <div className='w-full' >
        <ThirdSection />
      </div>
      <div className='w-full' >
        <FourthSection />
      </div>
      <div className='w-full' >
        <FifthSection />
      </div>
      <div className='w-full' >
        <SixthSection />
      </div>
      <div className='w-full' >
        <Footer />
      </div>
    </div>
  )
}

export default Home
